[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "lts"
rust = "stable"
uv = "latest"
pnpm = "latest"
aws-cli = "latest"

"npm:@google/gemini-cli" = "latest"
# "npm:@github/copilot" = "0.0.330"
"npm:@github/copilot" = "latest"
"npm:clipboard-cli" = "latest"
"npm:npm-check" = "latest"
"npm:trash-cli" = "latest"
"npm:git-graftree" = "latest"

# MCP
"npm:@upstash/context7-mcp" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:chrome-devtools-mcp" = "latest"
