[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "lts"
rust = "stable"
python = "latest"
uv = "latest"
pnpm = "latest"
aws-cli = "latest"
ni = "latest"

"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:clipboard-cli" = "latest"
"npm:trash-cli" = "latest"
"npm:git-graftree" = "latest"

# MCP
"npm:@playwright/mcp" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"

"npm:@sasazame/ccresume" = "latest"
"npm:opencode-ai" = "latest"
